apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-app
    release: canary
  name: demo-app-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
        release: canary
    spec:
      containers:
      - image: kshatrix/canary-demo
        name: demo-app
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
  labels:
    app: demo-app
    release: canary
  name: demo-app-canary
spec:
  ports:
  - name: http
    port: 80
  - name: http-metrics
    port: 8000
  selector:
    app: demo-app